SHELL=	/bin/ksh
#
CMD =   wsr_reformat
#
#FC =    xlf -qmaxmem=-1 
FC =    ifort
SRCS=	readin.f
OBJS=	readin.o

# Lines from here on down should not need to be changed.  They are the
# actual rules which make uses to build a.out.
#
all:	$(CMD)

$(CMD):	$(OBJS)
	$(FC) -o $(@) $(OBJS) 

# Make the profiled version of the command and call it a.out.prof
#
clean:
	-rm -f $(OBJS)

clobber:        clean
	-rm -f $(CMD)

void:   clobber
	-rm -f $(SRCS) makefile
