#!/bin/sh

###############################################################
# Runs WSR Main program
# Usage:JWSR_MAIN.sms.prod
# Change history log:
# 2006-12-12 Yucheng Song Modified for WSR 2007
##############################################################

date
export PS4='$SECONDS + $(basename ${0})[$LINENO]'
set -x

####################################
# Determine Job Output Name on System
####################################
export jobid=${jobid:-"$job.$PBS_JOBID"}
export pgmout="OUTPUT.${PBS_JOBID}"
export pgmerr=errfile
export ver=${ver:-$(echo ${wsr_ver:-v3.3.0}|cut -c1-4)}

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export RAWINSONDES=${RAWINSONDES:-NO}
export PRINTSDM=${PRINTSDM:-YES}
export XLFRTEOPTS="unit_vars=yes"

export NET=wsr
export RUN=wsr

export HOMEwsr=${HOMEwsr:-${PACKAGEROOT:?}/wsr.${wsr_ver:?}}
export EXECwsr=$HOMEwsr/exec
export FIXwsr=$HOMEwsr/fix

##############################
# Define for graphics
##############################
#export PATH=$PATH:/usrx/local/grads/bin
#export GADDIR=/usrx/local/grads/dat
#export GASCRP=/usrx/local/grads/gslib

##############################
# Define COM directories
##############################
#export COMIN_setup=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/setup
#export COMIN_setup=$(compath.py ${envir}/com/${NET}/${ver})/${RUN}.${PDY}/setup

##############################
# Run setpdy and initialize PDY variables
##############################
#export PDY=$(head -1 $COMIN_setup/targdata.d)
setpdy.sh
. ./PDY

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${ver})/${RUN}}
export COMIN_setup=${COMIN_setup:-$(compath.py ${envir}/com/${NET}/${ver})/setup}
#export COMIN_setup=${COMIN_setup:-$(compath.py ${envir}/com/${NET}/${ver})/${RUN}.${PDY}/setup}
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${ver})/${RUN}.${PDY}/main}

mkdir -p $COMOUT

#######################################################
# Special WSR VARS                                    #
# hhdiff: the ensemble date difference in hours       #
#      between EC and NCEP                            #
#      nvar is the total vars we have                 #
#      nv is the total vars we used for norm          #
#      nvr is the total number of points in VR region # 
#      Previously set to be 100 since 1000KM radius   # 
#      nd: no. of grid point drops if obs are taken   #
#######################################################
export idim=144
export jdim=37
export nd=25
export nvr=500
export hhdiff=00
export memec=51
export memnc=84
export memcm=42
export nv=9
export nvar=20
export nflights=90
export nrawin=34
export phase=1
if [[ $PDY -ge 20110226 ]]; then
	export phase=2
fi

export wsrmpexec=mpiexec #mpirun
echo wsrmpexec=$wsrmpexec

env|sort

########################################################
# Execute the script.
$HOMEwsr/scripts/exwsr_main.sh
export err=$?; err_chk
########################################################

if [ -s $pgmout ]; then
	cat $pgmout
fi

if [ "${KEEPDATA^^}" != "YES" ]; then
	rm -rf $DATA
fi

date

