#!/bin/ksh
#
# run one of the wsr jobs
#
echo `date` $0 $* begin
if (( $# >= 1 )); then
  job=$1
  args=good
  case $job in
    (ecmwfens)
      jobcardslist=wsr_ecmwfens.job
      chainsubmit=no
    ;;
    (ecmwf)
      jobcardslist=wsr_ecmwfens.job
      chainsubmit=no
    ;;
    (prep)
      jobcardslist=wsr_prep.job
      chainsubmit=no
    ;;
    (p)
      jobcardslist=wsr_prep.job
      chainsubmit=no
    ;;
    (main)
      jobcardslist=wsr_main.job
      chainsubmit=no
    ;;
    (m)
      jobcardslist=wsr_main.job
      chainsubmit=no
    ;;
    (pm)
      jobcardslist="wsr_prep.job wsr_main.job"
      chainsubmit=yes
    ;;
    (epm)
      jobcardslist="wsr_ecmwfens.job wsr_prep.job wsr_main.job"
      chainsubmit=yes
    ;;
    (*)
      args=bad
    ;;
  esac
  echo jobcardslist=$jobcardslist
  submit=no
  submit=yes
  renameold=yes
  renameold=no
  if (( $# >= 2 )); then
    flags=$2
    case $flags in
      (submit)
	submit=yes
      ;;
      (submitold)
	submit=yes
	renameold=no
      ;;
      (submitnew)
	submit=yes
      ;;
      (new)
	renameold=yes
      ;;
      (old)
	renameold=no
      ;;
      (*)
	args=bad
      ;;
    esac
  fi
  echo submit=$submit
  echo renameold=$renameold
  if [[ $args = good ]]; then
    chainfirst=yes
    for jobcards in $jobcardslist
    do
      echo `date` $0 $* set up directories for $jobcards
      dirc=`pwd`
      basedir=`dirname $dirc`
      basedird=`dirname $basedir`
      basedirdb=`basename $basedird`
      expid=$basedirdb
      echo expid=$expid
      localprefixsave=$basedird
      echo localprefixsave=$localprefixsave
      localprefixptmp=/ptmp/$LOGNAME/o/$expid
      echo localprefixptmp=$localprefixptmp
      if [[ -d $localprefixptmp ]]; then
	echo localprefixptmp=$localprefixptmp already exists
      else
	mkdir -p $localprefixptmp
      fi
      yyyymmdd=`date +%Y%m%d`
      echo yyyymmdd=$yyyymmdd
      if [[ -d $localprefixptmp/com/output/dev/$yyyymmdd ]]; then
	cleanall=yes
      else
	cleanall=no
      fi
      if [[ -d $localprefixptmp ]]; then
	cd $localprefixptmp
	rc=$?
	if (( rc == 0 )); then
	  pwd
	  if [[ $renameold = yes ]]; then
	    if [[ $chainfirst = yes ]] ; then
	      if [[ $cleanall = yes ]]; then
		cleanlist="tmpnwprd com/logs com/output/dev/$yyyymmdd com/mrf/dev/wsr.$yyyymmdd com/wsr/dev control nwges"
	      else
		cleanlist="tmpnwprd com/logs"
	      fi
	      dtg=`date +%Y%m%d%H%M%S`
	      echo dtg=$dtg
	      for dir in $cleanlist
	      do
		echo $dir rename before
		ls -ald ${dir}*
		if [[ -d $dir ]]; then
		  echo $dir remove if empty
		  find $dir -type d -depth -ls -exec rmdir {} \;
		  ls -ald ${dir}*
		fi
		if [[ -d $dir ]]; then
		  mv $dir $dir.$dtg
		fi
		echo $dir rename after
		ls -ald ${dir}*
	      done
	    fi
	  fi
	  gooddirs=yes
	  for dir in com/logs com/output/dev/today control tmpnwprd
	  do
	    echo $dir create before
	    mkdir -p $dir
	    rc=$?
	    if (( rc != 0 )); then
	      echo mkdir $dir FAILED rc=$rc
	      gooddirs=no
	    fi
	    echo $dir create after
	  done
	  if [[ $gooddirs = yes ]]; then
	    echo `date` $0 $* jobcards before
	    sed -e"s#EXPID#$expid#" \
		-e"s#OUTDAY#$outday#" \
		-e"s#LOCALPREFIXPTMP#$localprefixptmp#" \
		-e"s#LOCALPREFIXSAVE#$localprefixsave#" \
		-e"s#LOCALCHAINOPTION#$chainsubmit#" \
		$dirc/$jobcards > control/$jobcards
	    cat control/$jobcards
	    echo `date` $0 $* jobcards after
	    if [[ $submit = yes ]]; then
	      if [[ $chainfirst = yes ]]; then
		echo `date` $0 $* llsubmit before
		llsubmit control/$jobcards
		echo `date` $0 $* llsubmit after
	      fi
	    fi
	  else
	    echo SUBMIT SKIPPED BECAUSE gooddirs=$gooddirs
	  fi
	else
	  echo cd $localprefixptmp FAILED rc=$rc
	fi
      else
	echo localprefixptmp=$localprefixptmp DOES NOT EXIST
      fi
      chainfirst=no
      cd $dirc
    done
  fi
else
  args=bad
fi
if [[ $args = bad ]]; then
  echo one argument required: job
  ls -al wsr*job
fi
echo `date` $0 $* end
